# Site settings
name: Site Name
title: Site Title
email: ajkochanowicz@gmail.com
description: Site description.
username: ajkochanowicz
twitter_username: yourwebsitesUX
baseurl: ""
url: "http://example.com/"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
